name: 24/7 AI Daemon

on:
  workflow_dispatch: # Ручной запуск
  schedule:
    - cron: '0 */5 * * *' # Автоперезапуск каждые 5 часов

jobs:
  worker:
    runs-on: ubuntu-latest
    timeout-minutes: 340
    permissions:
      contents: write

    steps:
      - name: Чек-аут репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Установка библиотек
        run: |
          pip install -r requirements.txt

      - name: Запуск вечного демона
        run: |
          git config --global user.name "AI-Daemon"
          git config --global user.email "actions@github.com"
          python daemon.py
